// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  serverId: __t.u64(),
  name: __t.string(),
  topic: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const EncryptedChannelKey = __t.object("EncryptedChannelKey", {
  id: __t.u64(),
  channelId: __t.u64(),
  memberId: __t.identity(),
  encryptedKey: __t.string(),
});
export type EncryptedChannelKey = __Infer<typeof EncryptedChannelKey>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  channelId: __t.u64(),
  threadId: __t.u64(),
  senderId: __t.identity(),
  content: __t.string(),
  iv: __t.string(),
  sentAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const Server = __t.object("Server", {
  id: __t.u64(),
  name: __t.string(),
  ownerId: __t.identity(),
  iconColor: __t.string(),
  inviteCode: __t.string(),
  createdAt: __t.timestamp(),
});
export type Server = __Infer<typeof Server>;

export const ServerMember = __t.object("ServerMember", {
  id: __t.u64(),
  serverId: __t.u64(),
  memberId: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type ServerMember = __Infer<typeof ServerMember>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  channelId: __t.u64(),
  parentMessageId: __t.u64(),
  name: __t.string(),
  creatorId: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  avatarColor: __t.string(),
  online: __t.bool(),
  publicKey: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

