// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateChannelReducer from "../create_channel_reducer";
import CreateServerReducer from "../create_server_reducer";
import CreateThreadReducer from "../create_thread_reducer";
import DeleteChannelReducer from "../delete_channel_reducer";
import JoinServerReducer from "../join_server_reducer";
import LeaveServerReducer from "../leave_server_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetNameReducer from "../set_name_reducer";
import SetPublicKeyReducer from "../set_public_key_reducer";
import StoreChannelKeyReducer from "../store_channel_key_reducer";

export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateServerParams = __Infer<typeof CreateServerReducer>;
export type CreateThreadParams = __Infer<typeof CreateThreadReducer>;
export type DeleteChannelParams = __Infer<typeof DeleteChannelReducer>;
export type JoinServerParams = __Infer<typeof JoinServerReducer>;
export type LeaveServerParams = __Infer<typeof LeaveServerReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetPublicKeyParams = __Infer<typeof SetPublicKeyReducer>;
export type StoreChannelKeyParams = __Infer<typeof StoreChannelKeyReducer>;

